name: Update Coxies

# Schedule the workflow to run every 2.5 hours
on:
  schedule:
    - cron: '0 */2 * * *'    # Runs every 2 hours (at the start of the hour)
    - cron: '30 1-23/2 * * *' # Runs every 2 hours starting at 1:30 (2.5 hours after each run)
  workflow_dispatch:          # Allows manually triggering the workflow

jobs:
  update_proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run the update_proxies script
      run: |
        python update_coxies.py 
