name: Update Coxies

on:
  schedule:
    - cron: '0 */2 * * *'
    - cron: '30 1-23/2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_proxies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run the update_coxies script
      working-directory: ./
      run: |
        echo "Directory contents before running script:"
        ls -al
        python update_coxies.py
        echo "Directory contents after running script:"
        ls -al

    - name: Check for changes
      id: git-check
      run: |
        git status
        git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Commit and push if changed
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add coxies.txt
        git commit -m "Update coxies.txt"
        git push
